// Code generated by go-swagger; DO NOT EDIT.

package dfp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// DfpReadDfpReader is a Reader for the DfpReadDfp structure.
type DfpReadDfpReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DfpReadDfpReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDfpReadDfpOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDfpReadDfpNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDfpReadDfpInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /dfps/{id}] dfpReadDfp", response, response.Code())
	}
}

// NewDfpReadDfpOK creates a DfpReadDfpOK with default headers values
func NewDfpReadDfpOK() *DfpReadDfpOK {
	return &DfpReadDfpOK{}
}

/*
DfpReadDfpOK describes a response with status code 200, with default header values.

GET operation response
*/
type DfpReadDfpOK struct {
	Payload *models.AtcdfpDfpReadResponse
}

// IsSuccess returns true when this dfp read dfp o k response has a 2xx status code
func (o *DfpReadDfpOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this dfp read dfp o k response has a 3xx status code
func (o *DfpReadDfpOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dfp read dfp o k response has a 4xx status code
func (o *DfpReadDfpOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this dfp read dfp o k response has a 5xx status code
func (o *DfpReadDfpOK) IsServerError() bool {
	return false
}

// IsCode returns true when this dfp read dfp o k response a status code equal to that given
func (o *DfpReadDfpOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the dfp read dfp o k response
func (o *DfpReadDfpOK) Code() int {
	return 200
}

func (o *DfpReadDfpOK) Error() string {
	return fmt.Sprintf("[GET /dfps/{id}][%d] dfpReadDfpOK  %+v", 200, o.Payload)
}

func (o *DfpReadDfpOK) String() string {
	return fmt.Sprintf("[GET /dfps/{id}][%d] dfpReadDfpOK  %+v", 200, o.Payload)
}

func (o *DfpReadDfpOK) GetPayload() *models.AtcdfpDfpReadResponse {
	return o.Payload
}

func (o *DfpReadDfpOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AtcdfpDfpReadResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDfpReadDfpNotFound creates a DfpReadDfpNotFound with default headers values
func NewDfpReadDfpNotFound() *DfpReadDfpNotFound {
	return &DfpReadDfpNotFound{}
}

/*
	DfpReadDfpNotFound describes a response with status code 404, with default header values.

- 'id' value must contain existing DFP identifier
*/
type DfpReadDfpNotFound struct {
	Payload *DfpReadDfpNotFoundBody
}

// IsSuccess returns true when this dfp read dfp not found response has a 2xx status code
func (o *DfpReadDfpNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this dfp read dfp not found response has a 3xx status code
func (o *DfpReadDfpNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dfp read dfp not found response has a 4xx status code
func (o *DfpReadDfpNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this dfp read dfp not found response has a 5xx status code
func (o *DfpReadDfpNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this dfp read dfp not found response a status code equal to that given
func (o *DfpReadDfpNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the dfp read dfp not found response
func (o *DfpReadDfpNotFound) Code() int {
	return 404
}

func (o *DfpReadDfpNotFound) Error() string {
	return fmt.Sprintf("[GET /dfps/{id}][%d] dfpReadDfpNotFound  %+v", 404, o.Payload)
}

func (o *DfpReadDfpNotFound) String() string {
	return fmt.Sprintf("[GET /dfps/{id}][%d] dfpReadDfpNotFound  %+v", 404, o.Payload)
}

func (o *DfpReadDfpNotFound) GetPayload() *DfpReadDfpNotFoundBody {
	return o.Payload
}

func (o *DfpReadDfpNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DfpReadDfpNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDfpReadDfpInternalServerError creates a DfpReadDfpInternalServerError with default headers values
func NewDfpReadDfpInternalServerError() *DfpReadDfpInternalServerError {
	return &DfpReadDfpInternalServerError{}
}

/*
	DfpReadDfpInternalServerError describes a response with status code 500, with default header values.

- Internal server error occurred
*/
type DfpReadDfpInternalServerError struct {
	Payload *DfpReadDfpInternalServerErrorBody
}

// IsSuccess returns true when this dfp read dfp internal server error response has a 2xx status code
func (o *DfpReadDfpInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this dfp read dfp internal server error response has a 3xx status code
func (o *DfpReadDfpInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dfp read dfp internal server error response has a 4xx status code
func (o *DfpReadDfpInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this dfp read dfp internal server error response has a 5xx status code
func (o *DfpReadDfpInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this dfp read dfp internal server error response a status code equal to that given
func (o *DfpReadDfpInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the dfp read dfp internal server error response
func (o *DfpReadDfpInternalServerError) Code() int {
	return 500
}

func (o *DfpReadDfpInternalServerError) Error() string {
	return fmt.Sprintf("[GET /dfps/{id}][%d] dfpReadDfpInternalServerError  %+v", 500, o.Payload)
}

func (o *DfpReadDfpInternalServerError) String() string {
	return fmt.Sprintf("[GET /dfps/{id}][%d] dfpReadDfpInternalServerError  %+v", 500, o.Payload)
}

func (o *DfpReadDfpInternalServerError) GetPayload() *DfpReadDfpInternalServerErrorBody {
	return o.Payload
}

func (o *DfpReadDfpInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DfpReadDfpInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
DfpReadDfpInternalServerErrorBody dfp read dfp internal server error body
swagger:model DfpReadDfpInternalServerErrorBody
*/
type DfpReadDfpInternalServerErrorBody struct {

	// error
	Error *DfpReadDfpInternalServerErrorBodyError `json:"error,omitempty"`
}

// Validate validates this dfp read dfp internal server error body
func (o *DfpReadDfpInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DfpReadDfpInternalServerErrorBody) validateError(formats strfmt.Registry) error {
	if swag.IsZero(o.Error) { // not required
		return nil
	}

	if o.Error != nil {
		if err := o.Error.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("dfpReadDfpInternalServerError" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("dfpReadDfpInternalServerError" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this dfp read dfp internal server error body based on the context it is used
func (o *DfpReadDfpInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateError(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DfpReadDfpInternalServerErrorBody) contextValidateError(ctx context.Context, formats strfmt.Registry) error {

	if o.Error != nil {

		if swag.IsZero(o.Error) { // not required
			return nil
		}

		if err := o.Error.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("dfpReadDfpInternalServerError" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("dfpReadDfpInternalServerError" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DfpReadDfpInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DfpReadDfpInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res DfpReadDfpInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
DfpReadDfpInternalServerErrorBodyError dfp read dfp internal server error body error
swagger:model DfpReadDfpInternalServerErrorBodyError
*/
type DfpReadDfpInternalServerErrorBodyError struct {

	// code
	// Example: INTERNAL
	Code string `json:"code,omitempty"`

	// message
	// Example: Internal Server Error
	Message string `json:"message,omitempty"`

	// status
	// Example: 500
	Status string `json:"status,omitempty"`
}

// Validate validates this dfp read dfp internal server error body error
func (o *DfpReadDfpInternalServerErrorBodyError) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dfp read dfp internal server error body error based on context it is used
func (o *DfpReadDfpInternalServerErrorBodyError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DfpReadDfpInternalServerErrorBodyError) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DfpReadDfpInternalServerErrorBodyError) UnmarshalBinary(b []byte) error {
	var res DfpReadDfpInternalServerErrorBodyError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
DfpReadDfpNotFoundBody dfp read dfp not found body
swagger:model DfpReadDfpNotFoundBody
*/
type DfpReadDfpNotFoundBody struct {

	// error
	Error *DfpReadDfpNotFoundBodyError `json:"error,omitempty"`
}

// Validate validates this dfp read dfp not found body
func (o *DfpReadDfpNotFoundBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DfpReadDfpNotFoundBody) validateError(formats strfmt.Registry) error {
	if swag.IsZero(o.Error) { // not required
		return nil
	}

	if o.Error != nil {
		if err := o.Error.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("dfpReadDfpNotFound" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("dfpReadDfpNotFound" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this dfp read dfp not found body based on the context it is used
func (o *DfpReadDfpNotFoundBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateError(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DfpReadDfpNotFoundBody) contextValidateError(ctx context.Context, formats strfmt.Registry) error {

	if o.Error != nil {

		if swag.IsZero(o.Error) { // not required
			return nil
		}

		if err := o.Error.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("dfpReadDfpNotFound" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("dfpReadDfpNotFound" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DfpReadDfpNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DfpReadDfpNotFoundBody) UnmarshalBinary(b []byte) error {
	var res DfpReadDfpNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
DfpReadDfpNotFoundBodyError dfp read dfp not found body error
swagger:model DfpReadDfpNotFoundBodyError
*/
type DfpReadDfpNotFoundBodyError struct {

	// code
	// Example: NOT_FOUND
	Code string `json:"code,omitempty"`

	// message
	// Example: Dfp does not exist
	Message string `json:"message,omitempty"`

	// status
	// Example: 404
	Status string `json:"status,omitempty"`
}

// Validate validates this dfp read dfp not found body error
func (o *DfpReadDfpNotFoundBodyError) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dfp read dfp not found body error based on context it is used
func (o *DfpReadDfpNotFoundBodyError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DfpReadDfpNotFoundBodyError) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DfpReadDfpNotFoundBodyError) UnmarshalBinary(b []byte) error {
	var res DfpReadDfpNotFoundBodyError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
