// Code generated by go-swagger; DO NOT EDIT.

package services

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// ServicesReadReader is a Reader for the ServicesRead structure.
type ServicesReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ServicesReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewServicesReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /services/{id}] ServicesRead", response, response.Code())
	}
}

// NewServicesReadOK creates a ServicesReadOK with default headers values
func NewServicesReadOK() *ServicesReadOK {
	return &ServicesReadOK{}
}

/*
ServicesReadOK describes a response with status code 200, with default header values.

GET operation response
*/
type ServicesReadOK struct {
	Payload *models.InfraGetServiceResponse
}

// IsSuccess returns true when this services read o k response has a 2xx status code
func (o *ServicesReadOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this services read o k response has a 3xx status code
func (o *ServicesReadOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this services read o k response has a 4xx status code
func (o *ServicesReadOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this services read o k response has a 5xx status code
func (o *ServicesReadOK) IsServerError() bool {
	return false
}

// IsCode returns true when this services read o k response a status code equal to that given
func (o *ServicesReadOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the services read o k response
func (o *ServicesReadOK) Code() int {
	return 200
}

func (o *ServicesReadOK) Error() string {
	return fmt.Sprintf("[GET /services/{id}][%d] servicesReadOK  %+v", 200, o.Payload)
}

func (o *ServicesReadOK) String() string {
	return fmt.Sprintf("[GET /services/{id}][%d] servicesReadOK  %+v", 200, o.Payload)
}

func (o *ServicesReadOK) GetPayload() *models.InfraGetServiceResponse {
	return o.Payload
}

func (o *ServicesReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InfraGetServiceResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
