// Code generated by go-swagger; DO NOT EDIT.

package application_filters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewApplicationFiltersReadApplicationFilterParams creates a new ApplicationFiltersReadApplicationFilterParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewApplicationFiltersReadApplicationFilterParams() *ApplicationFiltersReadApplicationFilterParams {
	return &ApplicationFiltersReadApplicationFilterParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewApplicationFiltersReadApplicationFilterParamsWithTimeout creates a new ApplicationFiltersReadApplicationFilterParams object
// with the ability to set a timeout on a request.
func NewApplicationFiltersReadApplicationFilterParamsWithTimeout(timeout time.Duration) *ApplicationFiltersReadApplicationFilterParams {
	return &ApplicationFiltersReadApplicationFilterParams{
		timeout: timeout,
	}
}

// NewApplicationFiltersReadApplicationFilterParamsWithContext creates a new ApplicationFiltersReadApplicationFilterParams object
// with the ability to set a context for a request.
func NewApplicationFiltersReadApplicationFilterParamsWithContext(ctx context.Context) *ApplicationFiltersReadApplicationFilterParams {
	return &ApplicationFiltersReadApplicationFilterParams{
		Context: ctx,
	}
}

// NewApplicationFiltersReadApplicationFilterParamsWithHTTPClient creates a new ApplicationFiltersReadApplicationFilterParams object
// with the ability to set a custom HTTPClient for a request.
func NewApplicationFiltersReadApplicationFilterParamsWithHTTPClient(client *http.Client) *ApplicationFiltersReadApplicationFilterParams {
	return &ApplicationFiltersReadApplicationFilterParams{
		HTTPClient: client,
	}
}

/*
ApplicationFiltersReadApplicationFilterParams contains all the parameters to send to the API endpoint

	for the application filters read application filter operation.

	Typically these are written to a http.Request.
*/
type ApplicationFiltersReadApplicationFilterParams struct {

	/* Fields.



	A collection of response resources can be transformed by specifying a set of JSON tags to be returned. For a “flat” resource, the tag name is straightforward. If field selection is allowed on non-flat hierarchical resources, the service should implement a qualified naming scheme such as dot-qualification to reference data down the hierarchy. If a resource does not have the specified tag, the tag does not appear in the output resource.

	Specify this parameter as a comma-separated list of JSON tag names.


	*/
	Fields *string

	/* ID.

	   The Application Filter object identifier.

	   Format: int32
	*/
	ID int32

	/* Name.

	   The name of the application filter.
	*/
	Name *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the application filters read application filter params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ApplicationFiltersReadApplicationFilterParams) WithDefaults() *ApplicationFiltersReadApplicationFilterParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the application filters read application filter params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ApplicationFiltersReadApplicationFilterParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the application filters read application filter params
func (o *ApplicationFiltersReadApplicationFilterParams) WithTimeout(timeout time.Duration) *ApplicationFiltersReadApplicationFilterParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the application filters read application filter params
func (o *ApplicationFiltersReadApplicationFilterParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the application filters read application filter params
func (o *ApplicationFiltersReadApplicationFilterParams) WithContext(ctx context.Context) *ApplicationFiltersReadApplicationFilterParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the application filters read application filter params
func (o *ApplicationFiltersReadApplicationFilterParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the application filters read application filter params
func (o *ApplicationFiltersReadApplicationFilterParams) WithHTTPClient(client *http.Client) *ApplicationFiltersReadApplicationFilterParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the application filters read application filter params
func (o *ApplicationFiltersReadApplicationFilterParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the application filters read application filter params
func (o *ApplicationFiltersReadApplicationFilterParams) WithFields(fields *string) *ApplicationFiltersReadApplicationFilterParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the application filters read application filter params
func (o *ApplicationFiltersReadApplicationFilterParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithID adds the id to the application filters read application filter params
func (o *ApplicationFiltersReadApplicationFilterParams) WithID(id int32) *ApplicationFiltersReadApplicationFilterParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the application filters read application filter params
func (o *ApplicationFiltersReadApplicationFilterParams) SetID(id int32) {
	o.ID = id
}

// WithName adds the name to the application filters read application filter params
func (o *ApplicationFiltersReadApplicationFilterParams) WithName(name *string) *ApplicationFiltersReadApplicationFilterParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the application filters read application filter params
func (o *ApplicationFiltersReadApplicationFilterParams) SetName(name *string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *ApplicationFiltersReadApplicationFilterParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// query param _fields
		var qrFields string

		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {

			if err := r.SetQueryParam("_fields", qFields); err != nil {
				return err
			}
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if o.Name != nil {

		// query param name
		var qrName string

		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {

			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
