// Code generated by go-swagger; DO NOT EDIT.

package application_filters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// ApplicationFiltersUpdateApplicationFilterReader is a Reader for the ApplicationFiltersUpdateApplicationFilter structure.
type ApplicationFiltersUpdateApplicationFilterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ApplicationFiltersUpdateApplicationFilterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewApplicationFiltersUpdateApplicationFilterCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewApplicationFiltersUpdateApplicationFilterInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /application_filters/{id}] application_filtersUpdateApplicationFilter", response, response.Code())
	}
}

// NewApplicationFiltersUpdateApplicationFilterCreated creates a ApplicationFiltersUpdateApplicationFilterCreated with default headers values
func NewApplicationFiltersUpdateApplicationFilterCreated() *ApplicationFiltersUpdateApplicationFilterCreated {
	return &ApplicationFiltersUpdateApplicationFilterCreated{}
}

/*
ApplicationFiltersUpdateApplicationFilterCreated describes a response with status code 201, with default header values.

PUT operation response
*/
type ApplicationFiltersUpdateApplicationFilterCreated struct {
	Payload *models.AtcfwApplicationFilterUpdateResponse
}

// IsSuccess returns true when this application filters update application filter created response has a 2xx status code
func (o *ApplicationFiltersUpdateApplicationFilterCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this application filters update application filter created response has a 3xx status code
func (o *ApplicationFiltersUpdateApplicationFilterCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this application filters update application filter created response has a 4xx status code
func (o *ApplicationFiltersUpdateApplicationFilterCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this application filters update application filter created response has a 5xx status code
func (o *ApplicationFiltersUpdateApplicationFilterCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this application filters update application filter created response a status code equal to that given
func (o *ApplicationFiltersUpdateApplicationFilterCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the application filters update application filter created response
func (o *ApplicationFiltersUpdateApplicationFilterCreated) Code() int {
	return 201
}

func (o *ApplicationFiltersUpdateApplicationFilterCreated) Error() string {
	return fmt.Sprintf("[PUT /application_filters/{id}][%d] applicationFiltersUpdateApplicationFilterCreated  %+v", 201, o.Payload)
}

func (o *ApplicationFiltersUpdateApplicationFilterCreated) String() string {
	return fmt.Sprintf("[PUT /application_filters/{id}][%d] applicationFiltersUpdateApplicationFilterCreated  %+v", 201, o.Payload)
}

func (o *ApplicationFiltersUpdateApplicationFilterCreated) GetPayload() *models.AtcfwApplicationFilterUpdateResponse {
	return o.Payload
}

func (o *ApplicationFiltersUpdateApplicationFilterCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AtcfwApplicationFilterUpdateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewApplicationFiltersUpdateApplicationFilterInternalServerError creates a ApplicationFiltersUpdateApplicationFilterInternalServerError with default headers values
func NewApplicationFiltersUpdateApplicationFilterInternalServerError() *ApplicationFiltersUpdateApplicationFilterInternalServerError {
	return &ApplicationFiltersUpdateApplicationFilterInternalServerError{}
}

/*
	ApplicationFiltersUpdateApplicationFilterInternalServerError describes a response with status code 500, with default header values.

- Internal server error occurred
*/
type ApplicationFiltersUpdateApplicationFilterInternalServerError struct {
	Payload *ApplicationFiltersUpdateApplicationFilterInternalServerErrorBody
}

// IsSuccess returns true when this application filters update application filter internal server error response has a 2xx status code
func (o *ApplicationFiltersUpdateApplicationFilterInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this application filters update application filter internal server error response has a 3xx status code
func (o *ApplicationFiltersUpdateApplicationFilterInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this application filters update application filter internal server error response has a 4xx status code
func (o *ApplicationFiltersUpdateApplicationFilterInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this application filters update application filter internal server error response has a 5xx status code
func (o *ApplicationFiltersUpdateApplicationFilterInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this application filters update application filter internal server error response a status code equal to that given
func (o *ApplicationFiltersUpdateApplicationFilterInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the application filters update application filter internal server error response
func (o *ApplicationFiltersUpdateApplicationFilterInternalServerError) Code() int {
	return 500
}

func (o *ApplicationFiltersUpdateApplicationFilterInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /application_filters/{id}][%d] applicationFiltersUpdateApplicationFilterInternalServerError  %+v", 500, o.Payload)
}

func (o *ApplicationFiltersUpdateApplicationFilterInternalServerError) String() string {
	return fmt.Sprintf("[PUT /application_filters/{id}][%d] applicationFiltersUpdateApplicationFilterInternalServerError  %+v", 500, o.Payload)
}

func (o *ApplicationFiltersUpdateApplicationFilterInternalServerError) GetPayload() *ApplicationFiltersUpdateApplicationFilterInternalServerErrorBody {
	return o.Payload
}

func (o *ApplicationFiltersUpdateApplicationFilterInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ApplicationFiltersUpdateApplicationFilterInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
ApplicationFiltersUpdateApplicationFilterInternalServerErrorBody application filters update application filter internal server error body
swagger:model ApplicationFiltersUpdateApplicationFilterInternalServerErrorBody
*/
type ApplicationFiltersUpdateApplicationFilterInternalServerErrorBody struct {

	// error
	Error *ApplicationFiltersUpdateApplicationFilterInternalServerErrorBodyError `json:"error,omitempty"`
}

// Validate validates this application filters update application filter internal server error body
func (o *ApplicationFiltersUpdateApplicationFilterInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ApplicationFiltersUpdateApplicationFilterInternalServerErrorBody) validateError(formats strfmt.Registry) error {
	if swag.IsZero(o.Error) { // not required
		return nil
	}

	if o.Error != nil {
		if err := o.Error.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("applicationFiltersUpdateApplicationFilterInternalServerError" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("applicationFiltersUpdateApplicationFilterInternalServerError" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this application filters update application filter internal server error body based on the context it is used
func (o *ApplicationFiltersUpdateApplicationFilterInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateError(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ApplicationFiltersUpdateApplicationFilterInternalServerErrorBody) contextValidateError(ctx context.Context, formats strfmt.Registry) error {

	if o.Error != nil {

		if swag.IsZero(o.Error) { // not required
			return nil
		}

		if err := o.Error.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("applicationFiltersUpdateApplicationFilterInternalServerError" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("applicationFiltersUpdateApplicationFilterInternalServerError" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *ApplicationFiltersUpdateApplicationFilterInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ApplicationFiltersUpdateApplicationFilterInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res ApplicationFiltersUpdateApplicationFilterInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
ApplicationFiltersUpdateApplicationFilterInternalServerErrorBodyError application filters update application filter internal server error body error
swagger:model ApplicationFiltersUpdateApplicationFilterInternalServerErrorBodyError
*/
type ApplicationFiltersUpdateApplicationFilterInternalServerErrorBodyError struct {

	// code
	// Example: INTERNAL
	Code string `json:"code,omitempty"`

	// message
	// Example: Internal Server Error
	Message string `json:"message,omitempty"`

	// status
	// Example: 500
	Status string `json:"status,omitempty"`
}

// Validate validates this application filters update application filter internal server error body error
func (o *ApplicationFiltersUpdateApplicationFilterInternalServerErrorBodyError) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this application filters update application filter internal server error body error based on context it is used
func (o *ApplicationFiltersUpdateApplicationFilterInternalServerErrorBodyError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ApplicationFiltersUpdateApplicationFilterInternalServerErrorBodyError) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ApplicationFiltersUpdateApplicationFilterInternalServerErrorBodyError) UnmarshalBinary(b []byte) error {
	var res ApplicationFiltersUpdateApplicationFilterInternalServerErrorBodyError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
