// Code generated by go-swagger; DO NOT EDIT.

package hosts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// NewHostsCreateParams creates a new HostsCreateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewHostsCreateParams() *HostsCreateParams {
	return &HostsCreateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewHostsCreateParamsWithTimeout creates a new HostsCreateParams object
// with the ability to set a timeout on a request.
func NewHostsCreateParamsWithTimeout(timeout time.Duration) *HostsCreateParams {
	return &HostsCreateParams{
		timeout: timeout,
	}
}

// NewHostsCreateParamsWithContext creates a new HostsCreateParams object
// with the ability to set a context for a request.
func NewHostsCreateParamsWithContext(ctx context.Context) *HostsCreateParams {
	return &HostsCreateParams{
		Context: ctx,
	}
}

// NewHostsCreateParamsWithHTTPClient creates a new HostsCreateParams object
// with the ability to set a custom HTTPClient for a request.
func NewHostsCreateParamsWithHTTPClient(client *http.Client) *HostsCreateParams {
	return &HostsCreateParams{
		HTTPClient: client,
	}
}

/*
HostsCreateParams contains all the parameters to send to the API endpoint

	for the hosts create operation.

	Typically these are written to a http.Request.
*/
type HostsCreateParams struct {

	// Body.
	Body *models.InfraHost

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the hosts create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HostsCreateParams) WithDefaults() *HostsCreateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the hosts create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HostsCreateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the hosts create params
func (o *HostsCreateParams) WithTimeout(timeout time.Duration) *HostsCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the hosts create params
func (o *HostsCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the hosts create params
func (o *HostsCreateParams) WithContext(ctx context.Context) *HostsCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the hosts create params
func (o *HostsCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the hosts create params
func (o *HostsCreateParams) WithHTTPClient(client *http.Client) *HostsCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the hosts create params
func (o *HostsCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the hosts create params
func (o *HostsCreateParams) WithBody(body *models.InfraHost) *HostsCreateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the hosts create params
func (o *HostsCreateParams) SetBody(body *models.InfraHost) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *HostsCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
