// Code generated by go-swagger; DO NOT EDIT.

package named_list_items

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// NewNamedListItemsNamedListItemsPartialUpdateParams creates a new NamedListItemsNamedListItemsPartialUpdateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewNamedListItemsNamedListItemsPartialUpdateParams() *NamedListItemsNamedListItemsPartialUpdateParams {
	return &NamedListItemsNamedListItemsPartialUpdateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewNamedListItemsNamedListItemsPartialUpdateParamsWithTimeout creates a new NamedListItemsNamedListItemsPartialUpdateParams object
// with the ability to set a timeout on a request.
func NewNamedListItemsNamedListItemsPartialUpdateParamsWithTimeout(timeout time.Duration) *NamedListItemsNamedListItemsPartialUpdateParams {
	return &NamedListItemsNamedListItemsPartialUpdateParams{
		timeout: timeout,
	}
}

// NewNamedListItemsNamedListItemsPartialUpdateParamsWithContext creates a new NamedListItemsNamedListItemsPartialUpdateParams object
// with the ability to set a context for a request.
func NewNamedListItemsNamedListItemsPartialUpdateParamsWithContext(ctx context.Context) *NamedListItemsNamedListItemsPartialUpdateParams {
	return &NamedListItemsNamedListItemsPartialUpdateParams{
		Context: ctx,
	}
}

// NewNamedListItemsNamedListItemsPartialUpdateParamsWithHTTPClient creates a new NamedListItemsNamedListItemsPartialUpdateParams object
// with the ability to set a custom HTTPClient for a request.
func NewNamedListItemsNamedListItemsPartialUpdateParamsWithHTTPClient(client *http.Client) *NamedListItemsNamedListItemsPartialUpdateParams {
	return &NamedListItemsNamedListItemsPartialUpdateParams{
		HTTPClient: client,
	}
}

/*
NamedListItemsNamedListItemsPartialUpdateParams contains all the parameters to send to the API endpoint

	for the named list items named list items partial update operation.

	Typically these are written to a http.Request.
*/
type NamedListItemsNamedListItemsPartialUpdateParams struct {

	/* Body.

	   NamedListItemsPartialUpdate object
	*/
	Body *models.AtcfwNamedListItemsPartialUpdate

	/* ID.

	   The Named List object identifier.

	   Format: int32
	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the named list items named list items partial update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *NamedListItemsNamedListItemsPartialUpdateParams) WithDefaults() *NamedListItemsNamedListItemsPartialUpdateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the named list items named list items partial update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *NamedListItemsNamedListItemsPartialUpdateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the named list items named list items partial update params
func (o *NamedListItemsNamedListItemsPartialUpdateParams) WithTimeout(timeout time.Duration) *NamedListItemsNamedListItemsPartialUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the named list items named list items partial update params
func (o *NamedListItemsNamedListItemsPartialUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the named list items named list items partial update params
func (o *NamedListItemsNamedListItemsPartialUpdateParams) WithContext(ctx context.Context) *NamedListItemsNamedListItemsPartialUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the named list items named list items partial update params
func (o *NamedListItemsNamedListItemsPartialUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the named list items named list items partial update params
func (o *NamedListItemsNamedListItemsPartialUpdateParams) WithHTTPClient(client *http.Client) *NamedListItemsNamedListItemsPartialUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the named list items named list items partial update params
func (o *NamedListItemsNamedListItemsPartialUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the named list items named list items partial update params
func (o *NamedListItemsNamedListItemsPartialUpdateParams) WithBody(body *models.AtcfwNamedListItemsPartialUpdate) *NamedListItemsNamedListItemsPartialUpdateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the named list items named list items partial update params
func (o *NamedListItemsNamedListItemsPartialUpdateParams) SetBody(body *models.AtcfwNamedListItemsPartialUpdate) {
	o.Body = body
}

// WithID adds the id to the named list items named list items partial update params
func (o *NamedListItemsNamedListItemsPartialUpdateParams) WithID(id int32) *NamedListItemsNamedListItemsPartialUpdateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the named list items named list items partial update params
func (o *NamedListItemsNamedListItemsPartialUpdateParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *NamedListItemsNamedListItemsPartialUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
