// Code generated by go-swagger; DO NOT EDIT.

package security_policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// NewSecurityPoliciesCreateSecurityPolicyParams creates a new SecurityPoliciesCreateSecurityPolicyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSecurityPoliciesCreateSecurityPolicyParams() *SecurityPoliciesCreateSecurityPolicyParams {
	return &SecurityPoliciesCreateSecurityPolicyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSecurityPoliciesCreateSecurityPolicyParamsWithTimeout creates a new SecurityPoliciesCreateSecurityPolicyParams object
// with the ability to set a timeout on a request.
func NewSecurityPoliciesCreateSecurityPolicyParamsWithTimeout(timeout time.Duration) *SecurityPoliciesCreateSecurityPolicyParams {
	return &SecurityPoliciesCreateSecurityPolicyParams{
		timeout: timeout,
	}
}

// NewSecurityPoliciesCreateSecurityPolicyParamsWithContext creates a new SecurityPoliciesCreateSecurityPolicyParams object
// with the ability to set a context for a request.
func NewSecurityPoliciesCreateSecurityPolicyParamsWithContext(ctx context.Context) *SecurityPoliciesCreateSecurityPolicyParams {
	return &SecurityPoliciesCreateSecurityPolicyParams{
		Context: ctx,
	}
}

// NewSecurityPoliciesCreateSecurityPolicyParamsWithHTTPClient creates a new SecurityPoliciesCreateSecurityPolicyParams object
// with the ability to set a custom HTTPClient for a request.
func NewSecurityPoliciesCreateSecurityPolicyParamsWithHTTPClient(client *http.Client) *SecurityPoliciesCreateSecurityPolicyParams {
	return &SecurityPoliciesCreateSecurityPolicyParams{
		HTTPClient: client,
	}
}

/*
SecurityPoliciesCreateSecurityPolicyParams contains all the parameters to send to the API endpoint

	for the security policies create security policy operation.

	Typically these are written to a http.Request.
*/
type SecurityPoliciesCreateSecurityPolicyParams struct {

	/* Body.

	   The Security Policy object.
	*/
	Body *models.AtcfwSecurityPolicy

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the security policies create security policy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SecurityPoliciesCreateSecurityPolicyParams) WithDefaults() *SecurityPoliciesCreateSecurityPolicyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the security policies create security policy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SecurityPoliciesCreateSecurityPolicyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the security policies create security policy params
func (o *SecurityPoliciesCreateSecurityPolicyParams) WithTimeout(timeout time.Duration) *SecurityPoliciesCreateSecurityPolicyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the security policies create security policy params
func (o *SecurityPoliciesCreateSecurityPolicyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the security policies create security policy params
func (o *SecurityPoliciesCreateSecurityPolicyParams) WithContext(ctx context.Context) *SecurityPoliciesCreateSecurityPolicyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the security policies create security policy params
func (o *SecurityPoliciesCreateSecurityPolicyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the security policies create security policy params
func (o *SecurityPoliciesCreateSecurityPolicyParams) WithHTTPClient(client *http.Client) *SecurityPoliciesCreateSecurityPolicyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the security policies create security policy params
func (o *SecurityPoliciesCreateSecurityPolicyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the security policies create security policy params
func (o *SecurityPoliciesCreateSecurityPolicyParams) WithBody(body *models.AtcfwSecurityPolicy) *SecurityPoliciesCreateSecurityPolicyParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the security policies create security policy params
func (o *SecurityPoliciesCreateSecurityPolicyParams) SetBody(body *models.AtcfwSecurityPolicy) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *SecurityPoliciesCreateSecurityPolicyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
