// Code generated by go-swagger; DO NOT EDIT.

package security_policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// SecurityPoliciesListSecurityPoliciesReader is a Reader for the SecurityPoliciesListSecurityPolicies structure.
type SecurityPoliciesListSecurityPoliciesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SecurityPoliciesListSecurityPoliciesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSecurityPoliciesListSecurityPoliciesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewSecurityPoliciesListSecurityPoliciesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /security_policies] security_policiesListSecurityPolicies", response, response.Code())
	}
}

// NewSecurityPoliciesListSecurityPoliciesOK creates a SecurityPoliciesListSecurityPoliciesOK with default headers values
func NewSecurityPoliciesListSecurityPoliciesOK() *SecurityPoliciesListSecurityPoliciesOK {
	return &SecurityPoliciesListSecurityPoliciesOK{}
}

/*
SecurityPoliciesListSecurityPoliciesOK describes a response with status code 200, with default header values.

GET operation response
*/
type SecurityPoliciesListSecurityPoliciesOK struct {
	Payload *models.AtcfwSecurityPolicyMultiResponse
}

// IsSuccess returns true when this security policies list security policies o k response has a 2xx status code
func (o *SecurityPoliciesListSecurityPoliciesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this security policies list security policies o k response has a 3xx status code
func (o *SecurityPoliciesListSecurityPoliciesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this security policies list security policies o k response has a 4xx status code
func (o *SecurityPoliciesListSecurityPoliciesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this security policies list security policies o k response has a 5xx status code
func (o *SecurityPoliciesListSecurityPoliciesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this security policies list security policies o k response a status code equal to that given
func (o *SecurityPoliciesListSecurityPoliciesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the security policies list security policies o k response
func (o *SecurityPoliciesListSecurityPoliciesOK) Code() int {
	return 200
}

func (o *SecurityPoliciesListSecurityPoliciesOK) Error() string {
	return fmt.Sprintf("[GET /security_policies][%d] securityPoliciesListSecurityPoliciesOK  %+v", 200, o.Payload)
}

func (o *SecurityPoliciesListSecurityPoliciesOK) String() string {
	return fmt.Sprintf("[GET /security_policies][%d] securityPoliciesListSecurityPoliciesOK  %+v", 200, o.Payload)
}

func (o *SecurityPoliciesListSecurityPoliciesOK) GetPayload() *models.AtcfwSecurityPolicyMultiResponse {
	return o.Payload
}

func (o *SecurityPoliciesListSecurityPoliciesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AtcfwSecurityPolicyMultiResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSecurityPoliciesListSecurityPoliciesInternalServerError creates a SecurityPoliciesListSecurityPoliciesInternalServerError with default headers values
func NewSecurityPoliciesListSecurityPoliciesInternalServerError() *SecurityPoliciesListSecurityPoliciesInternalServerError {
	return &SecurityPoliciesListSecurityPoliciesInternalServerError{}
}

/*
	SecurityPoliciesListSecurityPoliciesInternalServerError describes a response with status code 500, with default header values.

- Internal server error occurred
*/
type SecurityPoliciesListSecurityPoliciesInternalServerError struct {
	Payload *SecurityPoliciesListSecurityPoliciesInternalServerErrorBody
}

// IsSuccess returns true when this security policies list security policies internal server error response has a 2xx status code
func (o *SecurityPoliciesListSecurityPoliciesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this security policies list security policies internal server error response has a 3xx status code
func (o *SecurityPoliciesListSecurityPoliciesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this security policies list security policies internal server error response has a 4xx status code
func (o *SecurityPoliciesListSecurityPoliciesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this security policies list security policies internal server error response has a 5xx status code
func (o *SecurityPoliciesListSecurityPoliciesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this security policies list security policies internal server error response a status code equal to that given
func (o *SecurityPoliciesListSecurityPoliciesInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the security policies list security policies internal server error response
func (o *SecurityPoliciesListSecurityPoliciesInternalServerError) Code() int {
	return 500
}

func (o *SecurityPoliciesListSecurityPoliciesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /security_policies][%d] securityPoliciesListSecurityPoliciesInternalServerError  %+v", 500, o.Payload)
}

func (o *SecurityPoliciesListSecurityPoliciesInternalServerError) String() string {
	return fmt.Sprintf("[GET /security_policies][%d] securityPoliciesListSecurityPoliciesInternalServerError  %+v", 500, o.Payload)
}

func (o *SecurityPoliciesListSecurityPoliciesInternalServerError) GetPayload() *SecurityPoliciesListSecurityPoliciesInternalServerErrorBody {
	return o.Payload
}

func (o *SecurityPoliciesListSecurityPoliciesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(SecurityPoliciesListSecurityPoliciesInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
SecurityPoliciesListSecurityPoliciesInternalServerErrorBody security policies list security policies internal server error body
swagger:model SecurityPoliciesListSecurityPoliciesInternalServerErrorBody
*/
type SecurityPoliciesListSecurityPoliciesInternalServerErrorBody struct {

	// error
	Error *SecurityPoliciesListSecurityPoliciesInternalServerErrorBodyError `json:"error,omitempty"`
}

// Validate validates this security policies list security policies internal server error body
func (o *SecurityPoliciesListSecurityPoliciesInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SecurityPoliciesListSecurityPoliciesInternalServerErrorBody) validateError(formats strfmt.Registry) error {
	if swag.IsZero(o.Error) { // not required
		return nil
	}

	if o.Error != nil {
		if err := o.Error.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("securityPoliciesListSecurityPoliciesInternalServerError" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("securityPoliciesListSecurityPoliciesInternalServerError" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this security policies list security policies internal server error body based on the context it is used
func (o *SecurityPoliciesListSecurityPoliciesInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateError(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SecurityPoliciesListSecurityPoliciesInternalServerErrorBody) contextValidateError(ctx context.Context, formats strfmt.Registry) error {

	if o.Error != nil {

		if swag.IsZero(o.Error) { // not required
			return nil
		}

		if err := o.Error.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("securityPoliciesListSecurityPoliciesInternalServerError" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("securityPoliciesListSecurityPoliciesInternalServerError" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *SecurityPoliciesListSecurityPoliciesInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SecurityPoliciesListSecurityPoliciesInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res SecurityPoliciesListSecurityPoliciesInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
SecurityPoliciesListSecurityPoliciesInternalServerErrorBodyError security policies list security policies internal server error body error
swagger:model SecurityPoliciesListSecurityPoliciesInternalServerErrorBodyError
*/
type SecurityPoliciesListSecurityPoliciesInternalServerErrorBodyError struct {

	// code
	// Example: INTERNAL
	Code string `json:"code,omitempty"`

	// message
	// Example: Internal Server Error
	Message string `json:"message,omitempty"`

	// status
	// Example: 500
	Status string `json:"status,omitempty"`
}

// Validate validates this security policies list security policies internal server error body error
func (o *SecurityPoliciesListSecurityPoliciesInternalServerErrorBodyError) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this security policies list security policies internal server error body error based on context it is used
func (o *SecurityPoliciesListSecurityPoliciesInternalServerErrorBodyError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *SecurityPoliciesListSecurityPoliciesInternalServerErrorBodyError) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SecurityPoliciesListSecurityPoliciesInternalServerErrorBodyError) UnmarshalBinary(b []byte) error {
	var res SecurityPoliciesListSecurityPoliciesInternalServerErrorBodyError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
