// Code generated by go-swagger; DO NOT EDIT.

package internal_domain_lists

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// InternalDomainListsListInternalDomainsReader is a Reader for the InternalDomainListsListInternalDomains structure.
type InternalDomainListsListInternalDomainsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *InternalDomainListsListInternalDomainsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewInternalDomainListsListInternalDomainsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewInternalDomainListsListInternalDomainsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /internal_domain_lists] internal_domain_listsListInternalDomains", response, response.Code())
	}
}

// NewInternalDomainListsListInternalDomainsOK creates a InternalDomainListsListInternalDomainsOK with default headers values
func NewInternalDomainListsListInternalDomainsOK() *InternalDomainListsListInternalDomainsOK {
	return &InternalDomainListsListInternalDomainsOK{}
}

/*
InternalDomainListsListInternalDomainsOK describes a response with status code 200, with default header values.

GET operation response
*/
type InternalDomainListsListInternalDomainsOK struct {
	Payload *models.AtcfwInternalDomainsMultiResponse
}

// IsSuccess returns true when this internal domain lists list internal domains o k response has a 2xx status code
func (o *InternalDomainListsListInternalDomainsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this internal domain lists list internal domains o k response has a 3xx status code
func (o *InternalDomainListsListInternalDomainsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this internal domain lists list internal domains o k response has a 4xx status code
func (o *InternalDomainListsListInternalDomainsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this internal domain lists list internal domains o k response has a 5xx status code
func (o *InternalDomainListsListInternalDomainsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this internal domain lists list internal domains o k response a status code equal to that given
func (o *InternalDomainListsListInternalDomainsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the internal domain lists list internal domains o k response
func (o *InternalDomainListsListInternalDomainsOK) Code() int {
	return 200
}

func (o *InternalDomainListsListInternalDomainsOK) Error() string {
	return fmt.Sprintf("[GET /internal_domain_lists][%d] internalDomainListsListInternalDomainsOK  %+v", 200, o.Payload)
}

func (o *InternalDomainListsListInternalDomainsOK) String() string {
	return fmt.Sprintf("[GET /internal_domain_lists][%d] internalDomainListsListInternalDomainsOK  %+v", 200, o.Payload)
}

func (o *InternalDomainListsListInternalDomainsOK) GetPayload() *models.AtcfwInternalDomainsMultiResponse {
	return o.Payload
}

func (o *InternalDomainListsListInternalDomainsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AtcfwInternalDomainsMultiResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewInternalDomainListsListInternalDomainsInternalServerError creates a InternalDomainListsListInternalDomainsInternalServerError with default headers values
func NewInternalDomainListsListInternalDomainsInternalServerError() *InternalDomainListsListInternalDomainsInternalServerError {
	return &InternalDomainListsListInternalDomainsInternalServerError{}
}

/*
	InternalDomainListsListInternalDomainsInternalServerError describes a response with status code 500, with default header values.

- Internal server error occurred
*/
type InternalDomainListsListInternalDomainsInternalServerError struct {
	Payload *InternalDomainListsListInternalDomainsInternalServerErrorBody
}

// IsSuccess returns true when this internal domain lists list internal domains internal server error response has a 2xx status code
func (o *InternalDomainListsListInternalDomainsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this internal domain lists list internal domains internal server error response has a 3xx status code
func (o *InternalDomainListsListInternalDomainsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this internal domain lists list internal domains internal server error response has a 4xx status code
func (o *InternalDomainListsListInternalDomainsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this internal domain lists list internal domains internal server error response has a 5xx status code
func (o *InternalDomainListsListInternalDomainsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this internal domain lists list internal domains internal server error response a status code equal to that given
func (o *InternalDomainListsListInternalDomainsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the internal domain lists list internal domains internal server error response
func (o *InternalDomainListsListInternalDomainsInternalServerError) Code() int {
	return 500
}

func (o *InternalDomainListsListInternalDomainsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /internal_domain_lists][%d] internalDomainListsListInternalDomainsInternalServerError  %+v", 500, o.Payload)
}

func (o *InternalDomainListsListInternalDomainsInternalServerError) String() string {
	return fmt.Sprintf("[GET /internal_domain_lists][%d] internalDomainListsListInternalDomainsInternalServerError  %+v", 500, o.Payload)
}

func (o *InternalDomainListsListInternalDomainsInternalServerError) GetPayload() *InternalDomainListsListInternalDomainsInternalServerErrorBody {
	return o.Payload
}

func (o *InternalDomainListsListInternalDomainsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(InternalDomainListsListInternalDomainsInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
InternalDomainListsListInternalDomainsInternalServerErrorBody internal domain lists list internal domains internal server error body
swagger:model InternalDomainListsListInternalDomainsInternalServerErrorBody
*/
type InternalDomainListsListInternalDomainsInternalServerErrorBody struct {

	// error
	Error *InternalDomainListsListInternalDomainsInternalServerErrorBodyError `json:"error,omitempty"`
}

// Validate validates this internal domain lists list internal domains internal server error body
func (o *InternalDomainListsListInternalDomainsInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *InternalDomainListsListInternalDomainsInternalServerErrorBody) validateError(formats strfmt.Registry) error {
	if swag.IsZero(o.Error) { // not required
		return nil
	}

	if o.Error != nil {
		if err := o.Error.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("internalDomainListsListInternalDomainsInternalServerError" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("internalDomainListsListInternalDomainsInternalServerError" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this internal domain lists list internal domains internal server error body based on the context it is used
func (o *InternalDomainListsListInternalDomainsInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateError(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *InternalDomainListsListInternalDomainsInternalServerErrorBody) contextValidateError(ctx context.Context, formats strfmt.Registry) error {

	if o.Error != nil {

		if swag.IsZero(o.Error) { // not required
			return nil
		}

		if err := o.Error.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("internalDomainListsListInternalDomainsInternalServerError" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("internalDomainListsListInternalDomainsInternalServerError" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *InternalDomainListsListInternalDomainsInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *InternalDomainListsListInternalDomainsInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res InternalDomainListsListInternalDomainsInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
InternalDomainListsListInternalDomainsInternalServerErrorBodyError internal domain lists list internal domains internal server error body error
swagger:model InternalDomainListsListInternalDomainsInternalServerErrorBodyError
*/
type InternalDomainListsListInternalDomainsInternalServerErrorBodyError struct {

	// code
	// Example: INTERNAL
	Code string `json:"code,omitempty"`

	// message
	// Example: Internal Server Error
	Message string `json:"message,omitempty"`

	// status
	// Example: 500
	Status string `json:"status,omitempty"`
}

// Validate validates this internal domain lists list internal domains internal server error body error
func (o *InternalDomainListsListInternalDomainsInternalServerErrorBodyError) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this internal domain lists list internal domains internal server error body error based on context it is used
func (o *InternalDomainListsListInternalDomainsInternalServerErrorBodyError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *InternalDomainListsListInternalDomainsInternalServerErrorBodyError) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *InternalDomainListsListInternalDomainsInternalServerErrorBodyError) UnmarshalBinary(b []byte) error {
	var res InternalDomainListsListInternalDomainsInternalServerErrorBodyError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
