// Code generated by go-swagger; DO NOT EDIT.

package category_filters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CategoryFiltersDeleteSingleCategoryFiltersReader is a Reader for the CategoryFiltersDeleteSingleCategoryFilters structure.
type CategoryFiltersDeleteSingleCategoryFiltersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CategoryFiltersDeleteSingleCategoryFiltersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewCategoryFiltersDeleteSingleCategoryFiltersNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCategoryFiltersDeleteSingleCategoryFiltersBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCategoryFiltersDeleteSingleCategoryFiltersInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /category_filters/{id}] category_filtersDeleteSingleCategoryFilters", response, response.Code())
	}
}

// NewCategoryFiltersDeleteSingleCategoryFiltersNoContent creates a CategoryFiltersDeleteSingleCategoryFiltersNoContent with default headers values
func NewCategoryFiltersDeleteSingleCategoryFiltersNoContent() *CategoryFiltersDeleteSingleCategoryFiltersNoContent {
	return &CategoryFiltersDeleteSingleCategoryFiltersNoContent{}
}

/*
CategoryFiltersDeleteSingleCategoryFiltersNoContent describes a response with status code 204, with default header values.

No Content
*/
type CategoryFiltersDeleteSingleCategoryFiltersNoContent struct {
}

// IsSuccess returns true when this category filters delete single category filters no content response has a 2xx status code
func (o *CategoryFiltersDeleteSingleCategoryFiltersNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this category filters delete single category filters no content response has a 3xx status code
func (o *CategoryFiltersDeleteSingleCategoryFiltersNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this category filters delete single category filters no content response has a 4xx status code
func (o *CategoryFiltersDeleteSingleCategoryFiltersNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this category filters delete single category filters no content response has a 5xx status code
func (o *CategoryFiltersDeleteSingleCategoryFiltersNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this category filters delete single category filters no content response a status code equal to that given
func (o *CategoryFiltersDeleteSingleCategoryFiltersNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the category filters delete single category filters no content response
func (o *CategoryFiltersDeleteSingleCategoryFiltersNoContent) Code() int {
	return 204
}

func (o *CategoryFiltersDeleteSingleCategoryFiltersNoContent) Error() string {
	return fmt.Sprintf("[DELETE /category_filters/{id}][%d] categoryFiltersDeleteSingleCategoryFiltersNoContent ", 204)
}

func (o *CategoryFiltersDeleteSingleCategoryFiltersNoContent) String() string {
	return fmt.Sprintf("[DELETE /category_filters/{id}][%d] categoryFiltersDeleteSingleCategoryFiltersNoContent ", 204)
}

func (o *CategoryFiltersDeleteSingleCategoryFiltersNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCategoryFiltersDeleteSingleCategoryFiltersBadRequest creates a CategoryFiltersDeleteSingleCategoryFiltersBadRequest with default headers values
func NewCategoryFiltersDeleteSingleCategoryFiltersBadRequest() *CategoryFiltersDeleteSingleCategoryFiltersBadRequest {
	return &CategoryFiltersDeleteSingleCategoryFiltersBadRequest{}
}

/*
	CategoryFiltersDeleteSingleCategoryFiltersBadRequest describes a response with status code 400, with default header values.

- 'id' value must contain values that are greater than or equal to zero
- 'ids' value must contain existing category filter identifiers
- category filter assigned to a security policy cannot be deleted
- category filter assigned to a bypass code cannot be deleted
*/
type CategoryFiltersDeleteSingleCategoryFiltersBadRequest struct {
	Payload *CategoryFiltersDeleteSingleCategoryFiltersBadRequestBody
}

// IsSuccess returns true when this category filters delete single category filters bad request response has a 2xx status code
func (o *CategoryFiltersDeleteSingleCategoryFiltersBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this category filters delete single category filters bad request response has a 3xx status code
func (o *CategoryFiltersDeleteSingleCategoryFiltersBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this category filters delete single category filters bad request response has a 4xx status code
func (o *CategoryFiltersDeleteSingleCategoryFiltersBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this category filters delete single category filters bad request response has a 5xx status code
func (o *CategoryFiltersDeleteSingleCategoryFiltersBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this category filters delete single category filters bad request response a status code equal to that given
func (o *CategoryFiltersDeleteSingleCategoryFiltersBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the category filters delete single category filters bad request response
func (o *CategoryFiltersDeleteSingleCategoryFiltersBadRequest) Code() int {
	return 400
}

func (o *CategoryFiltersDeleteSingleCategoryFiltersBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /category_filters/{id}][%d] categoryFiltersDeleteSingleCategoryFiltersBadRequest  %+v", 400, o.Payload)
}

func (o *CategoryFiltersDeleteSingleCategoryFiltersBadRequest) String() string {
	return fmt.Sprintf("[DELETE /category_filters/{id}][%d] categoryFiltersDeleteSingleCategoryFiltersBadRequest  %+v", 400, o.Payload)
}

func (o *CategoryFiltersDeleteSingleCategoryFiltersBadRequest) GetPayload() *CategoryFiltersDeleteSingleCategoryFiltersBadRequestBody {
	return o.Payload
}

func (o *CategoryFiltersDeleteSingleCategoryFiltersBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(CategoryFiltersDeleteSingleCategoryFiltersBadRequestBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCategoryFiltersDeleteSingleCategoryFiltersInternalServerError creates a CategoryFiltersDeleteSingleCategoryFiltersInternalServerError with default headers values
func NewCategoryFiltersDeleteSingleCategoryFiltersInternalServerError() *CategoryFiltersDeleteSingleCategoryFiltersInternalServerError {
	return &CategoryFiltersDeleteSingleCategoryFiltersInternalServerError{}
}

/*
	CategoryFiltersDeleteSingleCategoryFiltersInternalServerError describes a response with status code 500, with default header values.

- Internal server error occurred
*/
type CategoryFiltersDeleteSingleCategoryFiltersInternalServerError struct {
	Payload *CategoryFiltersDeleteSingleCategoryFiltersInternalServerErrorBody
}

// IsSuccess returns true when this category filters delete single category filters internal server error response has a 2xx status code
func (o *CategoryFiltersDeleteSingleCategoryFiltersInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this category filters delete single category filters internal server error response has a 3xx status code
func (o *CategoryFiltersDeleteSingleCategoryFiltersInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this category filters delete single category filters internal server error response has a 4xx status code
func (o *CategoryFiltersDeleteSingleCategoryFiltersInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this category filters delete single category filters internal server error response has a 5xx status code
func (o *CategoryFiltersDeleteSingleCategoryFiltersInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this category filters delete single category filters internal server error response a status code equal to that given
func (o *CategoryFiltersDeleteSingleCategoryFiltersInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the category filters delete single category filters internal server error response
func (o *CategoryFiltersDeleteSingleCategoryFiltersInternalServerError) Code() int {
	return 500
}

func (o *CategoryFiltersDeleteSingleCategoryFiltersInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /category_filters/{id}][%d] categoryFiltersDeleteSingleCategoryFiltersInternalServerError  %+v", 500, o.Payload)
}

func (o *CategoryFiltersDeleteSingleCategoryFiltersInternalServerError) String() string {
	return fmt.Sprintf("[DELETE /category_filters/{id}][%d] categoryFiltersDeleteSingleCategoryFiltersInternalServerError  %+v", 500, o.Payload)
}

func (o *CategoryFiltersDeleteSingleCategoryFiltersInternalServerError) GetPayload() *CategoryFiltersDeleteSingleCategoryFiltersInternalServerErrorBody {
	return o.Payload
}

func (o *CategoryFiltersDeleteSingleCategoryFiltersInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(CategoryFiltersDeleteSingleCategoryFiltersInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
CategoryFiltersDeleteSingleCategoryFiltersBadRequestBody category filters delete single category filters bad request body
swagger:model CategoryFiltersDeleteSingleCategoryFiltersBadRequestBody
*/
type CategoryFiltersDeleteSingleCategoryFiltersBadRequestBody struct {

	// error
	Error *CategoryFiltersDeleteSingleCategoryFiltersBadRequestBodyError `json:"error,omitempty"`
}

// Validate validates this category filters delete single category filters bad request body
func (o *CategoryFiltersDeleteSingleCategoryFiltersBadRequestBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CategoryFiltersDeleteSingleCategoryFiltersBadRequestBody) validateError(formats strfmt.Registry) error {
	if swag.IsZero(o.Error) { // not required
		return nil
	}

	if o.Error != nil {
		if err := o.Error.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("categoryFiltersDeleteSingleCategoryFiltersBadRequest" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("categoryFiltersDeleteSingleCategoryFiltersBadRequest" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this category filters delete single category filters bad request body based on the context it is used
func (o *CategoryFiltersDeleteSingleCategoryFiltersBadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateError(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CategoryFiltersDeleteSingleCategoryFiltersBadRequestBody) contextValidateError(ctx context.Context, formats strfmt.Registry) error {

	if o.Error != nil {

		if swag.IsZero(o.Error) { // not required
			return nil
		}

		if err := o.Error.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("categoryFiltersDeleteSingleCategoryFiltersBadRequest" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("categoryFiltersDeleteSingleCategoryFiltersBadRequest" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *CategoryFiltersDeleteSingleCategoryFiltersBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CategoryFiltersDeleteSingleCategoryFiltersBadRequestBody) UnmarshalBinary(b []byte) error {
	var res CategoryFiltersDeleteSingleCategoryFiltersBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
CategoryFiltersDeleteSingleCategoryFiltersBadRequestBodyError category filters delete single category filters bad request body error
swagger:model CategoryFiltersDeleteSingleCategoryFiltersBadRequestBodyError
*/
type CategoryFiltersDeleteSingleCategoryFiltersBadRequestBodyError struct {

	// code
	// Example: INVALID_ARGUMENT
	Code string `json:"code,omitempty"`

	// message
	// Example: invalid 'id': value must be greater than or equal to 0
	Message string `json:"message,omitempty"`

	// status
	// Example: 400
	Status string `json:"status,omitempty"`
}

// Validate validates this category filters delete single category filters bad request body error
func (o *CategoryFiltersDeleteSingleCategoryFiltersBadRequestBodyError) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this category filters delete single category filters bad request body error based on context it is used
func (o *CategoryFiltersDeleteSingleCategoryFiltersBadRequestBodyError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *CategoryFiltersDeleteSingleCategoryFiltersBadRequestBodyError) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CategoryFiltersDeleteSingleCategoryFiltersBadRequestBodyError) UnmarshalBinary(b []byte) error {
	var res CategoryFiltersDeleteSingleCategoryFiltersBadRequestBodyError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
CategoryFiltersDeleteSingleCategoryFiltersInternalServerErrorBody category filters delete single category filters internal server error body
swagger:model CategoryFiltersDeleteSingleCategoryFiltersInternalServerErrorBody
*/
type CategoryFiltersDeleteSingleCategoryFiltersInternalServerErrorBody struct {

	// error
	Error *CategoryFiltersDeleteSingleCategoryFiltersInternalServerErrorBodyError `json:"error,omitempty"`
}

// Validate validates this category filters delete single category filters internal server error body
func (o *CategoryFiltersDeleteSingleCategoryFiltersInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CategoryFiltersDeleteSingleCategoryFiltersInternalServerErrorBody) validateError(formats strfmt.Registry) error {
	if swag.IsZero(o.Error) { // not required
		return nil
	}

	if o.Error != nil {
		if err := o.Error.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("categoryFiltersDeleteSingleCategoryFiltersInternalServerError" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("categoryFiltersDeleteSingleCategoryFiltersInternalServerError" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this category filters delete single category filters internal server error body based on the context it is used
func (o *CategoryFiltersDeleteSingleCategoryFiltersInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateError(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CategoryFiltersDeleteSingleCategoryFiltersInternalServerErrorBody) contextValidateError(ctx context.Context, formats strfmt.Registry) error {

	if o.Error != nil {

		if swag.IsZero(o.Error) { // not required
			return nil
		}

		if err := o.Error.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("categoryFiltersDeleteSingleCategoryFiltersInternalServerError" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("categoryFiltersDeleteSingleCategoryFiltersInternalServerError" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *CategoryFiltersDeleteSingleCategoryFiltersInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CategoryFiltersDeleteSingleCategoryFiltersInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res CategoryFiltersDeleteSingleCategoryFiltersInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
CategoryFiltersDeleteSingleCategoryFiltersInternalServerErrorBodyError category filters delete single category filters internal server error body error
swagger:model CategoryFiltersDeleteSingleCategoryFiltersInternalServerErrorBodyError
*/
type CategoryFiltersDeleteSingleCategoryFiltersInternalServerErrorBodyError struct {

	// code
	// Example: INTERNAL
	Code string `json:"code,omitempty"`

	// message
	// Example: Internal Server Error
	Message string `json:"message,omitempty"`

	// status
	// Example: 500
	Status string `json:"status,omitempty"`
}

// Validate validates this category filters delete single category filters internal server error body error
func (o *CategoryFiltersDeleteSingleCategoryFiltersInternalServerErrorBodyError) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this category filters delete single category filters internal server error body error based on context it is used
func (o *CategoryFiltersDeleteSingleCategoryFiltersInternalServerErrorBodyError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *CategoryFiltersDeleteSingleCategoryFiltersInternalServerErrorBodyError) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CategoryFiltersDeleteSingleCategoryFiltersInternalServerErrorBodyError) UnmarshalBinary(b []byte) error {
	var res CategoryFiltersDeleteSingleCategoryFiltersInternalServerErrorBodyError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
