// Code generated by go-swagger; DO NOT EDIT.

package category_filters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewCategoryFiltersDeleteSingleCategoryFiltersParams creates a new CategoryFiltersDeleteSingleCategoryFiltersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCategoryFiltersDeleteSingleCategoryFiltersParams() *CategoryFiltersDeleteSingleCategoryFiltersParams {
	return &CategoryFiltersDeleteSingleCategoryFiltersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCategoryFiltersDeleteSingleCategoryFiltersParamsWithTimeout creates a new CategoryFiltersDeleteSingleCategoryFiltersParams object
// with the ability to set a timeout on a request.
func NewCategoryFiltersDeleteSingleCategoryFiltersParamsWithTimeout(timeout time.Duration) *CategoryFiltersDeleteSingleCategoryFiltersParams {
	return &CategoryFiltersDeleteSingleCategoryFiltersParams{
		timeout: timeout,
	}
}

// NewCategoryFiltersDeleteSingleCategoryFiltersParamsWithContext creates a new CategoryFiltersDeleteSingleCategoryFiltersParams object
// with the ability to set a context for a request.
func NewCategoryFiltersDeleteSingleCategoryFiltersParamsWithContext(ctx context.Context) *CategoryFiltersDeleteSingleCategoryFiltersParams {
	return &CategoryFiltersDeleteSingleCategoryFiltersParams{
		Context: ctx,
	}
}

// NewCategoryFiltersDeleteSingleCategoryFiltersParamsWithHTTPClient creates a new CategoryFiltersDeleteSingleCategoryFiltersParams object
// with the ability to set a custom HTTPClient for a request.
func NewCategoryFiltersDeleteSingleCategoryFiltersParamsWithHTTPClient(client *http.Client) *CategoryFiltersDeleteSingleCategoryFiltersParams {
	return &CategoryFiltersDeleteSingleCategoryFiltersParams{
		HTTPClient: client,
	}
}

/*
CategoryFiltersDeleteSingleCategoryFiltersParams contains all the parameters to send to the API endpoint

	for the category filters delete single category filters operation.

	Typically these are written to a http.Request.
*/
type CategoryFiltersDeleteSingleCategoryFiltersParams struct {

	/* ID.

	   The Category Filter object identifier.

	   Format: int32
	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the category filters delete single category filters params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CategoryFiltersDeleteSingleCategoryFiltersParams) WithDefaults() *CategoryFiltersDeleteSingleCategoryFiltersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the category filters delete single category filters params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CategoryFiltersDeleteSingleCategoryFiltersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the category filters delete single category filters params
func (o *CategoryFiltersDeleteSingleCategoryFiltersParams) WithTimeout(timeout time.Duration) *CategoryFiltersDeleteSingleCategoryFiltersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the category filters delete single category filters params
func (o *CategoryFiltersDeleteSingleCategoryFiltersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the category filters delete single category filters params
func (o *CategoryFiltersDeleteSingleCategoryFiltersParams) WithContext(ctx context.Context) *CategoryFiltersDeleteSingleCategoryFiltersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the category filters delete single category filters params
func (o *CategoryFiltersDeleteSingleCategoryFiltersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the category filters delete single category filters params
func (o *CategoryFiltersDeleteSingleCategoryFiltersParams) WithHTTPClient(client *http.Client) *CategoryFiltersDeleteSingleCategoryFiltersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the category filters delete single category filters params
func (o *CategoryFiltersDeleteSingleCategoryFiltersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the category filters delete single category filters params
func (o *CategoryFiltersDeleteSingleCategoryFiltersParams) WithID(id int32) *CategoryFiltersDeleteSingleCategoryFiltersParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the category filters delete single category filters params
func (o *CategoryFiltersDeleteSingleCategoryFiltersParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *CategoryFiltersDeleteSingleCategoryFiltersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
