// Code generated by go-swagger; DO NOT EDIT.

package detail

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// DetailHostListReader is a Reader for the DetailHostList structure.
type DetailHostListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DetailHostListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDetailHostListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /detail_hosts] DetailHostList", response, response.Code())
	}
}

// NewDetailHostListOK creates a DetailHostListOK with default headers values
func NewDetailHostListOK() *DetailHostListOK {
	return &DetailHostListOK{}
}

/*
DetailHostListOK describes a response with status code 200, with default header values.

GET operation response
*/
type DetailHostListOK struct {
	Payload *models.InfraListDetailHostsResponse
}

// IsSuccess returns true when this detail host list o k response has a 2xx status code
func (o *DetailHostListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this detail host list o k response has a 3xx status code
func (o *DetailHostListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this detail host list o k response has a 4xx status code
func (o *DetailHostListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this detail host list o k response has a 5xx status code
func (o *DetailHostListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this detail host list o k response a status code equal to that given
func (o *DetailHostListOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the detail host list o k response
func (o *DetailHostListOK) Code() int {
	return 200
}

func (o *DetailHostListOK) Error() string {
	return fmt.Sprintf("[GET /detail_hosts][%d] detailHostListOK  %+v", 200, o.Payload)
}

func (o *DetailHostListOK) String() string {
	return fmt.Sprintf("[GET /detail_hosts][%d] detailHostListOK  %+v", 200, o.Payload)
}

func (o *DetailHostListOK) GetPayload() *models.InfraListDetailHostsResponse {
	return o.Payload
}

func (o *DetailHostListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InfraListDetailHostsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
