// Code generated by go-swagger; DO NOT EDIT.

package network_lists

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// NewNetworkListsUpdateNetworkListParams creates a new NetworkListsUpdateNetworkListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewNetworkListsUpdateNetworkListParams() *NetworkListsUpdateNetworkListParams {
	return &NetworkListsUpdateNetworkListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewNetworkListsUpdateNetworkListParamsWithTimeout creates a new NetworkListsUpdateNetworkListParams object
// with the ability to set a timeout on a request.
func NewNetworkListsUpdateNetworkListParamsWithTimeout(timeout time.Duration) *NetworkListsUpdateNetworkListParams {
	return &NetworkListsUpdateNetworkListParams{
		timeout: timeout,
	}
}

// NewNetworkListsUpdateNetworkListParamsWithContext creates a new NetworkListsUpdateNetworkListParams object
// with the ability to set a context for a request.
func NewNetworkListsUpdateNetworkListParamsWithContext(ctx context.Context) *NetworkListsUpdateNetworkListParams {
	return &NetworkListsUpdateNetworkListParams{
		Context: ctx,
	}
}

// NewNetworkListsUpdateNetworkListParamsWithHTTPClient creates a new NetworkListsUpdateNetworkListParams object
// with the ability to set a custom HTTPClient for a request.
func NewNetworkListsUpdateNetworkListParamsWithHTTPClient(client *http.Client) *NetworkListsUpdateNetworkListParams {
	return &NetworkListsUpdateNetworkListParams{
		HTTPClient: client,
	}
}

/*
NetworkListsUpdateNetworkListParams contains all the parameters to send to the API endpoint

	for the network lists update network list operation.

	Typically these are written to a http.Request.
*/
type NetworkListsUpdateNetworkListParams struct {

	/* Body.

	   The Network List object.
	*/
	Body *models.AtcfwNetworkList

	/* ID.

	   The Network List object identifier.

	   Format: int32
	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the network lists update network list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *NetworkListsUpdateNetworkListParams) WithDefaults() *NetworkListsUpdateNetworkListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the network lists update network list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *NetworkListsUpdateNetworkListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the network lists update network list params
func (o *NetworkListsUpdateNetworkListParams) WithTimeout(timeout time.Duration) *NetworkListsUpdateNetworkListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the network lists update network list params
func (o *NetworkListsUpdateNetworkListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the network lists update network list params
func (o *NetworkListsUpdateNetworkListParams) WithContext(ctx context.Context) *NetworkListsUpdateNetworkListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the network lists update network list params
func (o *NetworkListsUpdateNetworkListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the network lists update network list params
func (o *NetworkListsUpdateNetworkListParams) WithHTTPClient(client *http.Client) *NetworkListsUpdateNetworkListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the network lists update network list params
func (o *NetworkListsUpdateNetworkListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the network lists update network list params
func (o *NetworkListsUpdateNetworkListParams) WithBody(body *models.AtcfwNetworkList) *NetworkListsUpdateNetworkListParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the network lists update network list params
func (o *NetworkListsUpdateNetworkListParams) SetBody(body *models.AtcfwNetworkList) {
	o.Body = body
}

// WithID adds the id to the network lists update network list params
func (o *NetworkListsUpdateNetworkListParams) WithID(id int32) *NetworkListsUpdateNetworkListParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the network lists update network list params
func (o *NetworkListsUpdateNetworkListParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *NetworkListsUpdateNetworkListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
