// Code generated by go-swagger; DO NOT EDIT.

package named_lists

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// NamedListsListNamedListsCSVReader is a Reader for the NamedListsListNamedListsCSV structure.
type NamedListsListNamedListsCSVReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *NamedListsListNamedListsCSVReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewNamedListsListNamedListsCSVOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewNamedListsListNamedListsCSVInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /named_lists_download] named_listsListNamedListsCSV", response, response.Code())
	}
}

// NewNamedListsListNamedListsCSVOK creates a NamedListsListNamedListsCSVOK with default headers values
func NewNamedListsListNamedListsCSVOK() *NamedListsListNamedListsCSVOK {
	return &NamedListsListNamedListsCSVOK{}
}

/*
NamedListsListNamedListsCSVOK describes a response with status code 200, with default header values.

GET operation response
*/
type NamedListsListNamedListsCSVOK struct {
	Payload *models.AtcfwNamedListCSVListResponse
}

// IsSuccess returns true when this named lists list named lists c s v o k response has a 2xx status code
func (o *NamedListsListNamedListsCSVOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this named lists list named lists c s v o k response has a 3xx status code
func (o *NamedListsListNamedListsCSVOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this named lists list named lists c s v o k response has a 4xx status code
func (o *NamedListsListNamedListsCSVOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this named lists list named lists c s v o k response has a 5xx status code
func (o *NamedListsListNamedListsCSVOK) IsServerError() bool {
	return false
}

// IsCode returns true when this named lists list named lists c s v o k response a status code equal to that given
func (o *NamedListsListNamedListsCSVOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the named lists list named lists c s v o k response
func (o *NamedListsListNamedListsCSVOK) Code() int {
	return 200
}

func (o *NamedListsListNamedListsCSVOK) Error() string {
	return fmt.Sprintf("[GET /named_lists_download][%d] namedListsListNamedListsCSVOK  %+v", 200, o.Payload)
}

func (o *NamedListsListNamedListsCSVOK) String() string {
	return fmt.Sprintf("[GET /named_lists_download][%d] namedListsListNamedListsCSVOK  %+v", 200, o.Payload)
}

func (o *NamedListsListNamedListsCSVOK) GetPayload() *models.AtcfwNamedListCSVListResponse {
	return o.Payload
}

func (o *NamedListsListNamedListsCSVOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AtcfwNamedListCSVListResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewNamedListsListNamedListsCSVInternalServerError creates a NamedListsListNamedListsCSVInternalServerError with default headers values
func NewNamedListsListNamedListsCSVInternalServerError() *NamedListsListNamedListsCSVInternalServerError {
	return &NamedListsListNamedListsCSVInternalServerError{}
}

/*
	NamedListsListNamedListsCSVInternalServerError describes a response with status code 500, with default header values.

- Internal server error occurred
*/
type NamedListsListNamedListsCSVInternalServerError struct {
	Payload *NamedListsListNamedListsCSVInternalServerErrorBody
}

// IsSuccess returns true when this named lists list named lists c s v internal server error response has a 2xx status code
func (o *NamedListsListNamedListsCSVInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this named lists list named lists c s v internal server error response has a 3xx status code
func (o *NamedListsListNamedListsCSVInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this named lists list named lists c s v internal server error response has a 4xx status code
func (o *NamedListsListNamedListsCSVInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this named lists list named lists c s v internal server error response has a 5xx status code
func (o *NamedListsListNamedListsCSVInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this named lists list named lists c s v internal server error response a status code equal to that given
func (o *NamedListsListNamedListsCSVInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the named lists list named lists c s v internal server error response
func (o *NamedListsListNamedListsCSVInternalServerError) Code() int {
	return 500
}

func (o *NamedListsListNamedListsCSVInternalServerError) Error() string {
	return fmt.Sprintf("[GET /named_lists_download][%d] namedListsListNamedListsCSVInternalServerError  %+v", 500, o.Payload)
}

func (o *NamedListsListNamedListsCSVInternalServerError) String() string {
	return fmt.Sprintf("[GET /named_lists_download][%d] namedListsListNamedListsCSVInternalServerError  %+v", 500, o.Payload)
}

func (o *NamedListsListNamedListsCSVInternalServerError) GetPayload() *NamedListsListNamedListsCSVInternalServerErrorBody {
	return o.Payload
}

func (o *NamedListsListNamedListsCSVInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(NamedListsListNamedListsCSVInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
NamedListsListNamedListsCSVInternalServerErrorBody named lists list named lists c s v internal server error body
swagger:model NamedListsListNamedListsCSVInternalServerErrorBody
*/
type NamedListsListNamedListsCSVInternalServerErrorBody struct {

	// error
	Error *NamedListsListNamedListsCSVInternalServerErrorBodyError `json:"error,omitempty"`
}

// Validate validates this named lists list named lists c s v internal server error body
func (o *NamedListsListNamedListsCSVInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *NamedListsListNamedListsCSVInternalServerErrorBody) validateError(formats strfmt.Registry) error {
	if swag.IsZero(o.Error) { // not required
		return nil
	}

	if o.Error != nil {
		if err := o.Error.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("namedListsListNamedListsCSVInternalServerError" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("namedListsListNamedListsCSVInternalServerError" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this named lists list named lists c s v internal server error body based on the context it is used
func (o *NamedListsListNamedListsCSVInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateError(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *NamedListsListNamedListsCSVInternalServerErrorBody) contextValidateError(ctx context.Context, formats strfmt.Registry) error {

	if o.Error != nil {

		if swag.IsZero(o.Error) { // not required
			return nil
		}

		if err := o.Error.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("namedListsListNamedListsCSVInternalServerError" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("namedListsListNamedListsCSVInternalServerError" + "." + "error")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *NamedListsListNamedListsCSVInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *NamedListsListNamedListsCSVInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res NamedListsListNamedListsCSVInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
NamedListsListNamedListsCSVInternalServerErrorBodyError named lists list named lists c s v internal server error body error
swagger:model NamedListsListNamedListsCSVInternalServerErrorBodyError
*/
type NamedListsListNamedListsCSVInternalServerErrorBodyError struct {

	// code
	// Example: INTERNAL
	Code string `json:"code,omitempty"`

	// message
	// Example: Internal Server Error
	Message string `json:"message,omitempty"`

	// status
	// Example: 500
	Status string `json:"status,omitempty"`
}

// Validate validates this named lists list named lists c s v internal server error body error
func (o *NamedListsListNamedListsCSVInternalServerErrorBodyError) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this named lists list named lists c s v internal server error body error based on context it is used
func (o *NamedListsListNamedListsCSVInternalServerErrorBodyError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *NamedListsListNamedListsCSVInternalServerErrorBodyError) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *NamedListsListNamedListsCSVInternalServerErrorBodyError) UnmarshalBinary(b []byte) error {
	var res NamedListsListNamedListsCSVInternalServerErrorBodyError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
