// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AtcfwListSeverityLevels The Payload for Patch Operation to update Threat/Confidence Levels and Tags in TI List
//
// swagger:model atcfwListSeverityLevels
type AtcfwListSeverityLevels struct {

	// The confidence level for a TI list. The possible values are [LOW", "MEDIUM", "HIGH"]
	// Example: LOW
	ConfidenceLevel string `json:"confidence_level,omitempty"`

	// The Named List object identifier.
	// Read Only: true
	ID int32 `json:"id,omitempty"`

	// Enables tag support for resource where tags attribute contains user-defined key value pairs
	Tags interface{} `json:"tags,omitempty"`

	// The threat level for a TI list. The possible values are ["INFO", "LOW", "MEDIUM", "HIGH"]
	// Example: INFO
	ThreatLevel string `json:"threat_level,omitempty"`
}

// Validate validates this atcfw list severity levels
func (m *AtcfwListSeverityLevels) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validate this atcfw list severity levels based on the context it is used
func (m *AtcfwListSeverityLevels) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AtcfwListSeverityLevels) contextValidateID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "id", "body", int32(m.ID)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AtcfwListSeverityLevels) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AtcfwListSeverityLevels) UnmarshalBinary(b []byte) error {
	var res AtcfwListSeverityLevels
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
