// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AtcfwAppApprovalsUpdateRequest atcfw app approvals update request
//
// swagger:model atcfwAppApprovalsUpdateRequest
type AtcfwAppApprovalsUpdateRequest struct {

	// Field Mask.
	Fields *ProtobufFieldMask `json:"fields,omitempty"`

	// inserted approvals
	InsertedApprovals []*AtcfwAppApproval `json:"inserted_approvals"`

	// removed approvals
	RemovedApprovals []*AtcfwAppApprovalRemovalRequest `json:"removed_approvals"`
}

// Validate validates this atcfw app approvals update request
func (m *AtcfwAppApprovalsUpdateRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFields(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInsertedApprovals(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRemovedApprovals(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AtcfwAppApprovalsUpdateRequest) validateFields(formats strfmt.Registry) error {
	if swag.IsZero(m.Fields) { // not required
		return nil
	}

	if m.Fields != nil {
		if err := m.Fields.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("fields")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("fields")
			}
			return err
		}
	}

	return nil
}

func (m *AtcfwAppApprovalsUpdateRequest) validateInsertedApprovals(formats strfmt.Registry) error {
	if swag.IsZero(m.InsertedApprovals) { // not required
		return nil
	}

	for i := 0; i < len(m.InsertedApprovals); i++ {
		if swag.IsZero(m.InsertedApprovals[i]) { // not required
			continue
		}

		if m.InsertedApprovals[i] != nil {
			if err := m.InsertedApprovals[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("inserted_approvals" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("inserted_approvals" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *AtcfwAppApprovalsUpdateRequest) validateRemovedApprovals(formats strfmt.Registry) error {
	if swag.IsZero(m.RemovedApprovals) { // not required
		return nil
	}

	for i := 0; i < len(m.RemovedApprovals); i++ {
		if swag.IsZero(m.RemovedApprovals[i]) { // not required
			continue
		}

		if m.RemovedApprovals[i] != nil {
			if err := m.RemovedApprovals[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("removed_approvals" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("removed_approvals" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this atcfw app approvals update request based on the context it is used
func (m *AtcfwAppApprovalsUpdateRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateFields(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateInsertedApprovals(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRemovedApprovals(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AtcfwAppApprovalsUpdateRequest) contextValidateFields(ctx context.Context, formats strfmt.Registry) error {

	if m.Fields != nil {

		if swag.IsZero(m.Fields) { // not required
			return nil
		}

		if err := m.Fields.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("fields")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("fields")
			}
			return err
		}
	}

	return nil
}

func (m *AtcfwAppApprovalsUpdateRequest) contextValidateInsertedApprovals(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.InsertedApprovals); i++ {

		if m.InsertedApprovals[i] != nil {

			if swag.IsZero(m.InsertedApprovals[i]) { // not required
				return nil
			}

			if err := m.InsertedApprovals[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("inserted_approvals" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("inserted_approvals" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *AtcfwAppApprovalsUpdateRequest) contextValidateRemovedApprovals(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.RemovedApprovals); i++ {

		if m.RemovedApprovals[i] != nil {

			if swag.IsZero(m.RemovedApprovals[i]) { // not required
				return nil
			}

			if err := m.RemovedApprovals[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("removed_approvals" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("removed_approvals" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *AtcfwAppApprovalsUpdateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AtcfwAppApprovalsUpdateRequest) UnmarshalBinary(b []byte) error {
	var res AtcfwAppApprovalsUpdateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
