// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AtcfwNamedListItemsPartialUpdate atcfw named list items partial update
//
// swagger:model atcfwNamedListItemsPartialUpdate
type AtcfwNamedListItemsPartialUpdate struct {

	// The List of ItemStructs structure which contains the item and its description
	// Example: [{"description":"Item 1 Description","item":"example2.somedomain.com"},{"description":"Item 2 Description","item":"193.56.2.10/32"},{"description":"Item 3 Description","item":"2000:db8:ffff:ffff:ffff:ffff:ffff:fff1/128"},{"description":"Item 4 Description","item":"193.56.2.9"}]
	DeletedItemsDescribed []*AtcfwItemStructs `json:"deleted_items_described"`

	// The Named List object identifier.
	// Read Only: true
	ID int32 `json:"id,omitempty"`

	// The List of ItemStructs structure which contains the item and its description
	// Example: [{"description":"Item 1 Description","item":"example1.somedomain.com"},{"description":"Item 2 Description","item":"193.56.2.11/32"},{"description":"Item 3 Description","item":"2001:db8:ffff:ffff:ffff:ffff:ffff:fff1/128"},{"description":"Item 4 Description","item":"193.56.2.11"}]
	InsertedItemsDescribed []*AtcfwItemStructs `json:"inserted_items_described"`
}

// Validate validates this atcfw named list items partial update
func (m *AtcfwNamedListItemsPartialUpdate) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDeletedItemsDescribed(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInsertedItemsDescribed(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AtcfwNamedListItemsPartialUpdate) validateDeletedItemsDescribed(formats strfmt.Registry) error {
	if swag.IsZero(m.DeletedItemsDescribed) { // not required
		return nil
	}

	for i := 0; i < len(m.DeletedItemsDescribed); i++ {
		if swag.IsZero(m.DeletedItemsDescribed[i]) { // not required
			continue
		}

		if m.DeletedItemsDescribed[i] != nil {
			if err := m.DeletedItemsDescribed[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("deleted_items_described" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("deleted_items_described" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *AtcfwNamedListItemsPartialUpdate) validateInsertedItemsDescribed(formats strfmt.Registry) error {
	if swag.IsZero(m.InsertedItemsDescribed) { // not required
		return nil
	}

	for i := 0; i < len(m.InsertedItemsDescribed); i++ {
		if swag.IsZero(m.InsertedItemsDescribed[i]) { // not required
			continue
		}

		if m.InsertedItemsDescribed[i] != nil {
			if err := m.InsertedItemsDescribed[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("inserted_items_described" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("inserted_items_described" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this atcfw named list items partial update based on the context it is used
func (m *AtcfwNamedListItemsPartialUpdate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDeletedItemsDescribed(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateInsertedItemsDescribed(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AtcfwNamedListItemsPartialUpdate) contextValidateDeletedItemsDescribed(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.DeletedItemsDescribed); i++ {

		if m.DeletedItemsDescribed[i] != nil {

			if swag.IsZero(m.DeletedItemsDescribed[i]) { // not required
				return nil
			}

			if err := m.DeletedItemsDescribed[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("deleted_items_described" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("deleted_items_described" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *AtcfwNamedListItemsPartialUpdate) contextValidateID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "id", "body", int32(m.ID)); err != nil {
		return err
	}

	return nil
}

func (m *AtcfwNamedListItemsPartialUpdate) contextValidateInsertedItemsDescribed(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.InsertedItemsDescribed); i++ {

		if m.InsertedItemsDescribed[i] != nil {

			if swag.IsZero(m.InsertedItemsDescribed[i]) { // not required
				return nil
			}

			if err := m.InsertedItemsDescribed[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("inserted_items_described" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("inserted_items_described" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *AtcfwNamedListItemsPartialUpdate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AtcfwNamedListItemsPartialUpdate) UnmarshalBinary(b []byte) error {
	var res AtcfwNamedListItemsPartialUpdate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
