// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AtcfwInternalDomainsDeleteRequest The Internal Domains delete request.
//
// swagger:model atcfwInternalDomainsDeleteRequest
type AtcfwInternalDomainsDeleteRequest struct {

	// The list of InternalDomains object identifiers.
	// Example: [12345,53215]
	Ids []int32 `json:"ids"`
}

// Validate validates this atcfw internal domains delete request
func (m *AtcfwInternalDomainsDeleteRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this atcfw internal domains delete request based on context it is used
func (m *AtcfwInternalDomainsDeleteRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AtcfwInternalDomainsDeleteRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AtcfwInternalDomainsDeleteRequest) UnmarshalBinary(b []byte) error {
	var res AtcfwInternalDomainsDeleteRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
