// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AtcfwNamedListRead The Named List object.
//
// The Named List object represents several types of lists allowed for BloxOne Cloud such as predefined threat intelligence feeds that your subscription offers (Threat Insight, Fast Flux, DGA, DNSM). In addition to the predefined threat intelligence feeds that your subscription offers, you can create custom lists (containing domains and IP addresses) to define whitelists and blacklists for additional protection. You can use a custom list to complement existing feeds or override the Block, Allow, Log, or Redirect action that is currently defined for an existing feed. Note that lists representing predefined TI feeds cannot be created, updated and deleted.
//
// swagger:model atcfwNamedListRead
type AtcfwNamedListRead struct {

	// The confidence level for a custom list. The possible values are ["LOW", "MEDIUM", "HIGH"]
	// Example: LOW
	// Read Only: true
	ConfidenceLevel string `json:"confidence_level,omitempty"`

	// The time when this Named List object was created.
	// Read Only: true
	// Format: date-time
	CreatedTime strfmt.DateTime `json:"created_time,omitempty"`

	// The brief description for the named list.
	// Example: Named List A Description
	// Read Only: true
	Description string `json:"description,omitempty"`

	// The Named List object identifier.
	// Read Only: true
	ID int32 `json:"id,omitempty"`

	// The number of items in this named list.
	// Example: 24567
	// Read Only: true
	ItemCount int32 `json:"item_count,omitempty"`

	// The name of the named list.
	// Example: named_list_a
	// Read Only: true
	Name string `json:"name,omitempty"`

	// The list of the security policy names with which the named list is associated.
	// Example: ["security_policy_a","security_policy_b"]
	// Read Only: true
	Policies []string `json:"policies"`

	// Tags associated with this Named List
	Tags interface{} `json:"tags,omitempty"`

	// The threat level for a custom list. The possible values are ["INFO", "LOW", "MEDIUM", "HIGH"]
	// Example: INFO
	// Read Only: true
	ThreatLevel string `json:"threat_level,omitempty"`

	// The type of the named list, that can be "custom_list", "threat_insight", "fast_flux", "dga" or "dnsm".
	// Example: custom_list
	// Read Only: true
	// Enum: [custom_list threat_insight fast_flux dga dnsm]
	Type string `json:"type,omitempty"`

	// The time when this Named List object was last updated.
	// Read Only: true
	// Format: date-time
	UpdatedTime strfmt.DateTime `json:"updated_time,omitempty"`
}

// Validate validates this atcfw named list read
func (m *AtcfwNamedListRead) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreatedTime(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdatedTime(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AtcfwNamedListRead) validateCreatedTime(formats strfmt.Registry) error {
	if swag.IsZero(m.CreatedTime) { // not required
		return nil
	}

	if err := validate.FormatOf("created_time", "body", "date-time", m.CreatedTime.String(), formats); err != nil {
		return err
	}

	return nil
}

var atcfwNamedListReadTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["custom_list","threat_insight","fast_flux","dga","dnsm"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		atcfwNamedListReadTypeTypePropEnum = append(atcfwNamedListReadTypeTypePropEnum, v)
	}
}

const (

	// AtcfwNamedListReadTypeCustomList captures enum value "custom_list"
	AtcfwNamedListReadTypeCustomList string = "custom_list"

	// AtcfwNamedListReadTypeThreatInsight captures enum value "threat_insight"
	AtcfwNamedListReadTypeThreatInsight string = "threat_insight"

	// AtcfwNamedListReadTypeFastFlux captures enum value "fast_flux"
	AtcfwNamedListReadTypeFastFlux string = "fast_flux"

	// AtcfwNamedListReadTypeDga captures enum value "dga"
	AtcfwNamedListReadTypeDga string = "dga"

	// AtcfwNamedListReadTypeDnsm captures enum value "dnsm"
	AtcfwNamedListReadTypeDnsm string = "dnsm"
)

// prop value enum
func (m *AtcfwNamedListRead) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, atcfwNamedListReadTypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *AtcfwNamedListRead) validateType(formats strfmt.Registry) error {
	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

func (m *AtcfwNamedListRead) validateUpdatedTime(formats strfmt.Registry) error {
	if swag.IsZero(m.UpdatedTime) { // not required
		return nil
	}

	if err := validate.FormatOf("updated_time", "body", "date-time", m.UpdatedTime.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this atcfw named list read based on the context it is used
func (m *AtcfwNamedListRead) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateConfidenceLevel(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCreatedTime(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDescription(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateItemCount(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateName(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePolicies(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateThreatLevel(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUpdatedTime(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AtcfwNamedListRead) contextValidateConfidenceLevel(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "confidence_level", "body", string(m.ConfidenceLevel)); err != nil {
		return err
	}

	return nil
}

func (m *AtcfwNamedListRead) contextValidateCreatedTime(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "created_time", "body", strfmt.DateTime(m.CreatedTime)); err != nil {
		return err
	}

	return nil
}

func (m *AtcfwNamedListRead) contextValidateDescription(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "description", "body", string(m.Description)); err != nil {
		return err
	}

	return nil
}

func (m *AtcfwNamedListRead) contextValidateID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "id", "body", int32(m.ID)); err != nil {
		return err
	}

	return nil
}

func (m *AtcfwNamedListRead) contextValidateItemCount(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "item_count", "body", int32(m.ItemCount)); err != nil {
		return err
	}

	return nil
}

func (m *AtcfwNamedListRead) contextValidateName(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "name", "body", string(m.Name)); err != nil {
		return err
	}

	return nil
}

func (m *AtcfwNamedListRead) contextValidatePolicies(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "policies", "body", []string(m.Policies)); err != nil {
		return err
	}

	return nil
}

func (m *AtcfwNamedListRead) contextValidateThreatLevel(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "threat_level", "body", string(m.ThreatLevel)); err != nil {
		return err
	}

	return nil
}

func (m *AtcfwNamedListRead) contextValidateType(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "type", "body", string(m.Type)); err != nil {
		return err
	}

	return nil
}

func (m *AtcfwNamedListRead) contextValidateUpdatedTime(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "updated_time", "body", strfmt.DateTime(m.UpdatedTime)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AtcfwNamedListRead) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AtcfwNamedListRead) UnmarshalBinary(b []byte) error {
	var res AtcfwNamedListRead
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
