// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AtcfwAccessCodeRule atcfw access code rule
//
// swagger:model atcfwAccessCodeRule
type AtcfwAccessCodeRule struct {

	// action
	Action string `json:"action,omitempty"`

	// data
	Data string `json:"data,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// redirect name
	RedirectName string `json:"redirect_name,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this atcfw access code rule
func (m *AtcfwAccessCodeRule) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this atcfw access code rule based on context it is used
func (m *AtcfwAccessCodeRule) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AtcfwAccessCodeRule) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AtcfwAccessCodeRule) UnmarshalBinary(b []byte) error {
	var res AtcfwAccessCodeRule
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
